package com.mantledillusion.vaadin.cotton.component.css;

public enum CssCursor implements CssEnumValue {

    ALIAS,
    ALL_SCROLL,
    CELL,
    COL_RESIZE,
    COPY,
    CROSSHAIR,
    DEFAULT,
    E_RESIZE,
    EW_RESIZE,
    GRAB,
    GRABBING,
    HELP,
    INHERIT,
    MOVE,
    N_RESIZE,
    NE_RESIZE,
    NESW_RESIZE,
    NO_DROP,
    NONE,
    NOT_ALLOWED,
    NS_RESIZE,
    NW_RESIZE,
    NWSE_RESIZE,
    POINTER,
    PROGRESS,
    ROW_SIZE,
    S_RESIZE,
    SE_RESIZE,
    SW_RESIZE,
    TEXT,
    VERTICAL_TEXT,
    W_RESIZE,
    WAIT,
    ZOOM_IN,
    ZOOM_OUT
}
